#include "std_types.h"
#include "rcc_interface.h"
#include "rcc_cnfg.h"

#define SW_CLEAR						(u32)0xFFFFFFFC

#define HSEDIV2_VAL					(u8)2

#define	PLLXTPRE_CLEAR			(u32)0xFF7FFFFF

#define PLLMULL_CFGR_CLEAR		(u32)0xFFC3FFFF

#define MCO_OFFSET_CLEAR		(u32)0xF8FFFFFF
#define	MCO_NO_CLOCK				(u32)0
#define	MCO_SYS_CLOCK				(u32)0x4000000
#define	MCO_HSI_CLOCK				(u32)0x5000000
#define	MCO_HSE_CLOCK				(u32)0x6000000
#define	MCO_PLL_CLOCK				(u32)0x7000000

#define	APB2_PRESCHALER_PIN		(u8)11

#define APB2_CFGR_CLEAR			(u32)0xFFFFF8FF

#define	APB1_PRESCHALER_PIN		(u8)8

#define APB1_CFGR_CLEAR			(u32)0xFFFFC7FF

#define	AHB_PRESCHALER_PIN		(u8)4

#define AHB_CFGR_CLEAR			(u32)0xFFFFFF0F

#define PLLSRC_CLEAR	(u32)0xFFF4FFFF

#define BASE_ADDRESS	0x40021000

typedef struct
{
	u32 CR;
	u32 CFGR;
	u32 CIR;
	u32 APB2RSTR;
	u32 APB1RSTR;
	u32 AHBENR;
	u32 APB2ENR;
	u32 APB1ENR;
	u32 BDCR;
	u32 CSR;
}RCCstruct;

static volatile RCCstruct* RCC = (volatile RCCstruct*) BASE_ADDRESS;



/*
HSION_VAL	
HSEON_VAL	
PLLON_VAL	
*/
void rcc_voidEnableClock(u32 clockSource)
{
	RCC->CR |= clockSource;
}

/*
HSION_CLEAR
HSEON_CLEAR
PLLON_CLEAR

*/
void rcc_voidDisableClock(u32 clockSourceMask)
{
	RCC->CR &= clockSourceMask;
}

/*
HSI_VAL
HSE_VAL
PLL_VAL
*/

void rcc_voidSelectSysClock(u32 clockSource)
{
	u8 temp = RCC->CFGR;
	temp &= SW_CLEAR;
	temp |= clockSource;
	RCC->CFGR = temp;
}


/*
 * HSIRDY
	HSERDY
	PLLRDY
*/

#define	RCC_CLK_RDY_TIMEOUT			10000u
ErrorStatus rcc_errClockReady(u32 clock)
{
	u16 counter=0;
	u8 status = OK;
	while((!(RCC->CR&clock))&&(counter < RCC_CLK_RDY_TIMEOUT))
		counter++;
	if(counter >= RCC_CLK_RDY_TIMEOUT)status = NOK;
	return status;
}

/*
PLLSRC_HSI
PLLSRC_HSE
PLLSRC_HSEDIV2
*/

void rcc_voidPllSource (u32 pllsrc)
{
	u32 temp = RCC->CFGR;
	temp &= PLLSRC_CLEAR;
	temp |= pllsrc;
	RCC->CFGR = temp;
}


/*
PLLMUL2	
PLLMUL3	
PLLMUL4	
PLLMUL5	
PLLMUL6	
PLLMUL7	
PLLMUL8	
PLLMUL9	
PLLMUL10
PLLMUL11
PLLMUL12
PLLMUL13
PLLMUL14
PLLMUL15
PLLMUL16
*/

void rcc_voidPllMultiplier(u32 pllmul)
{
	RCC->CFGR &= (PLLMULL_CFGR_CLEAR);
	RCC->CFGR |= (pllmul);
}
/*
DMA1EN_AHBENR	
DMA2EN_AHBENR	
SRAMEN_AHBENR	
FLITFEN_AHBENR
CRCEEN_AHBENR	
FSMCEN_AHBENR	
SDIOEN_AHBENR	
*/
void rcc_voidEnablePeripheralAHB (u32 peripheral)
{
	RCC->AHBENR|=peripheral;
}

/*

DMA1EN_AHBENR_DISABLE	
DMA2EN_AHBENR_DISABLE	
SRAMEN_AHBENR_DISABLE	
FLITFEN_AHBENR_DISABLE
CRCEEN_AHBENR_DISABLE	
FSMCEN_AHBENR_DISABLE	
SDIOEN_AHBENR_DISABLE	

*/


void rcc_voidDisablePeripheralAHB (u32 peripheral)
{
	RCC->AHBENR &= peripheral;
}

/*
AFIOEN_APB2ENR	
IOPAEN_APB2ENR	
IOPBEN_APB2ENR	
IOPCEN_APB2ENR	
IOPDEN_APB2ENR	
IOPEEN_APB2ENR	
IOPFEN_APB2ENR	
IOPGEN_APB2ENR	
ADC1EN_APB2ENR	
ADC2EN_APB2ENR	
TIM1EN_APB2ENR	
SPI1EN_APB2ENR	
TIM8EN_APB2ENR	
USART1EN_APB2ENR
ADC3EN_APB2ENR	
TIM9EN_APB2ENR	
TIM10EN_APB2ENR	
TIM11EN_APB2ENR	
*/

void rcc_voidEnablePeripheralAPB2 (u32 peripheral)
{
	RCC->APB2ENR|=peripheral;
}

/*
AFIOEN_APB2ENR_DISABLE	
IOPAEN_APB2ENR_DISABLE	
IOPBEN_APB2ENR_DISABLE	
IOPCEN_APB2ENR_DISABLE	
IOPDEN_APB2ENR_DISABLE	
IOPEEN_APB2ENR_DISABLE	
IOPFEN_APB2ENR_DISABLE	
IOPGEN_APB2ENR_DISABLE	
ADC1EN_APB2ENR_DISABLE	
ADC2EN_APB2ENR_DISABLE	
TIM1EN_APB2ENR_DISABLE	
SPI1EN_APB2ENR_DISABLE	
TIM8EN_APB2ENR_DISABLE	
USART1EN_APB2ENR_DISABLE
ADC3EN_APB2ENR_DISABLE	
TIM9EN_APB2ENR_DISABLE	
TIM10EN_APB2ENR_DISABLE	
TIM11EN_APB2ENR_DISABLE	

*/

void rcc_voidDisablePeripheralAPB2 (u32 peripheral)
{
	RCC->APB2ENR&=peripheral;
}

/*
TIM2EN_APB1ENR	
TIM3EN_APB1ENR	
TIM4EN_APB1ENR	
TIM5EN_APB1ENR	
TIM6EN_APB1ENR	
TIM7EN_APB1ENR	
TIM12EN_APB1ENR	
TIM13EN_APB1ENR	
TIM14EN_APB1ENR	
WWDEN_APB1ENR		
SPI2EN_APB1ENR	
USART2EN_APB1ENR
USART3EN_APB1ENR
I2C1EN_APB1ENR	
I2C2EN_APB1ENR	
USBEN_APB1ENR		
CANEN_APB1ENR		
BKPEN_APB1ENR		
PWREN_APB1ENR		
DACEN_APB1ENR		
*/


void rcc_voidEnablePeripheralAPB1 (u32 peripheral)
{
	RCC->APB1ENR|=peripheral;
}

/*

TIM2EN_APB1ENR_DISABLE	
TIM3EN_APB1ENR_DISABLE	
TIM4EN_APB1ENR_DISABLE	
TIM5EN_APB1ENR_DISABLE	
TIM6EN_APB1ENR_DISABLE	
TIM7EN_APB1ENR_DISABLE	
TIM12EN_APB1ENR_DISABLE	
TIM13EN_APB1ENR_DISABLE	
TIM14EN_APB1ENR_DISABLE	
WWDEN_APB1ENR_DISABLE		
SPI2EN_APB1ENR_DISABLE	
USART2EN_APB1ENR_DISABLE
USART3EN_APB1ENR_DISABLE
I2C1EN_APB1ENR_DISABLE	
I2C2EN_APB1ENR_DISABLE	
USBEN_APB1ENR_DISABLE		
CANEN_APB1ENR_DISABLE		
BKPEN_APB1ENR_DISABLE		
PWREN_APB1ENR_DISABLE		
DACEN_APB1ENR_DISABLE		

*/



void rcc_voidDisablePeripheralAPB1 (u32 peripheral)
{
	RCC->APB2ENR&=peripheral;
}


/*
MCO_NO_CLOCK	
MCO_SYS_CLOCK	
MCO_HSI_CLOCK	
MCO_HSE_CLOCK	
MCO_PLL_CLOCK	
*/

void rcc_voidsetMCO(u32 mcosrc)
{
	RCC->CFGR &= MCO_OFFSET_CLEAR;
	RCC->CFGR |= mcosrc;
}

/*
AHB_NO_DIVISOR	
AHB_2_DIVISOR		
AHB_4_DIVISOR		
AHB_8_DIVISOR		
AHB_16_DIVISOR	
AHB_64_DIVISOR	
AHB_128_DIVISOR
AHB_256_DIVISOR
AHB_512_DIVISOR
*/

void rcc_voidAHBprescaler(u32 prescaler)
{
		RCC->CFGR &= AHB_CFGR_CLEAR;
		RCC->CFGR |= prescaler;
}


/*

APB2_NO_DIVISOR	
APB2_2_DIVISOR	
APB2_4_DIVISOR	
APB2_8_DIVISOR	
APB2_16_DIVISOR	

*/

void rcc_voidAPB2prescaler(u32 prescaler)
{
	RCC->CFGR &=(APB2_CFGR_CLEAR);
	RCC->CFGR |= prescaler;
}


/*

APB1_NO_DIVISOR	
APB1_2_DIVISOR	
APB1_4_DIVISOR	
APB1_8_DIVISOR	
APB1_16_DIVISOR	

*/

void rcc_voidAPB1prescaler(u32 prescaler)
{
	RCC->CFGR &=(APB1_CFGR_CLEAR);
	RCC->CFGR |= prescaler;
}

#define	RCC_SWS_CLOCK_MASK		(u8)0b1100




u8 rcc_u8GetCurrentClock(void)
{
	u32 currentClock = RCC->CFGR & RCC_SWS_CLOCK_MASK ;
	return ((u8)currentClock);
}

u32 rcc_u32GetPLLMultiplier(void)
{
	u32 pllmul = (RCC->CFGR & 0x3C0000);
	return pllmul;
}

u32 rcc_u32GetPLLSource(void)
{
	u32 pllsource = (RCC->CFGR & 0x30000);
	return pllsource;
}

u16 rcc_u16GetAHBPreschaler(void)
{
	u16 currentPreschaler = ((RCC->CFGR)&(0xFF<<4));
	return currentPreschaler;
}

